# Generated by Django 2.2.6 on 2019-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplatedetection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobilenumber', models.IntegerField(max_length=100)),
            ],
        ),
    ]
