# Generated by Django 2.2.6 on 2019-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberplatedetection', '0003_auto_20191119_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='mobilenumber',
            field=models.BigIntegerField(max_length=100),
        ),
    ]
